const NEW_POST_REQUEST_PENDING = "NEW_POST_REQUEST_PENDING";
const NEW_POST_REQUEST_FAILURE = "NEW_POST_REQUEST_FAILURE";
const NEW_POST_REQUEST_SUCCESS = "NEW_POST_REQUEST_SUCCESS";
const USER_DATA = "USER_DATA";


export default {
    NEW_POST_REQUEST_FAILURE,
    NEW_POST_REQUEST_PENDING,
    NEW_POST_REQUEST_SUCCESS,
    USER_DATA
}